# Generated by Django 5.1.4 on 2024-12-19 03:39

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(help_text='Título do Documento com até 100 caractéres', max_length=100, unique=True, verbose_name='Título do Documento')),
                ('description', models.TextField(blank=True, help_text='Descrição do documento não obrigatória', max_length=2000, null=True, verbose_name='Descrição do documento')),
                ('document', models.FileField(help_text='Proibido o upload de arquivos dos tipos: .exe, .zip e .bat', upload_to='', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('documents'), models.Model),
        ),
    ]
