# Generated by Django 5.1.4 on 2024-12-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_documents_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Ativo', verbose_name='Ativo'),
        ),
    ]
